---
#==============================================================================+
# Description : Role to run server tasks for a FreeIPA install
#
# Supported OS: EL7
#
# Created by: Panxatony
#
#==============================================================================+


# pre-reqs

- name: upgrade all packages
  yum: name=* state=latest

- name: install IPA software group
  yum: name={{item}} state=present
  with_items:
     - libselinux-python
     - libsemanage-python

- name: Ensure SELinux is enabled in `enforcing` mode.
  selinux: policy=targeted state=enforcing

- name: Ensure httpd can connect to the network.
  seboolean: name=httpd_can_network_connect state=yes persistent=yes

# install FreeIPA
- include: set-system-hostname.yml
- include: set-hosts.yml
- include: set-resolv.conf.yml
- include: set-timeserver.yml
- include: install-free-ipa.yml
- include: set-firewall.yml
- include: free-ipa-setup.yml

# update Schema to support vSphere

- include: add-schema-vsphere.yml
  tags:
     -vsphere