---
#==============================================================================+
# Description : Role to run server tasks for a FreeIPA install
#
# Supported OS: EL7
#
# Created by: Panxatony
#
#==============================================================================+


# pre-reqs

- name: upgrade all packages
  yum: name=* state=latest
  become: yes
  become_user: root
  tags:
    - freeipa

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  become: yes
  become_user: root
  tags:
    - freeipa

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  become: yes
  become_user: root
  tags:
    - freeipa

- name: install IPA software group
  yum: name={{item}} state=present
  with_items:
     - libselinux-python
     - libsemanage-python
  become: yes
  become_user: root
  tags:
    - freeipa

- name: Ensure SELinux is enabled in `enforcing` mode.
  selinux: policy=targeted state=enforcing
  become: yes
  become_user: root
  tags:
    - freeipa

- name: Ensure httpd can connect to the network.
  seboolean: name=httpd_can_network_connect state=yes persistent=yes
  become: yes
  become_user: root
  tags:
    - freeipa

# install FreeIPA
- include: set-system-hostname.yml tags=freeipa
- include: set-hosts.yml tags=freeipa
- include: set-resolv.conf.yml tags=freeipa
- include: set-timeserver.yml tags=freeipa
- include: install-free-ipa.yml tags=freeipa
- include: set-firewall.yml tags=freeipa
- include: free-ipa-setup.yml tags=freeipa

# update Schema to support vSphere

- include: add-schema-vsphere.yml tags=freeipa
  when: freeipa_vsphere_modify == true
