---
#==============================================================================+
# Description : Playbook to run server tasks for a FreeIPA install
#
# Supported OS: EL7
#
# Created by: Panxatony
#
#==============================================================================+

- name: Creates the /etc/resolv.conf file 
  template: src=etc-resolv.conf.j2 dest=/etc/resolv.conf
  become: yes
  become_user: root
  tags:
    - freeipa