---
#==============================================================================+
# Description : Playbook to run server tasks for a FreeIPA install
#
# Supported OS: EL7
#
# Created by: Panxatony
#
#==============================================================================+


- name: Creates the /etc/hostname file 
  template: src=etc-hostname.j2 dest=/etc/hostname owner=root group=root mode=0644
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  become: yes
  become_user: root
  tags:
    - freeipa
