---
#==============================================================================+
# Description : Playbook to run server tasks for a FreeIPA install
#
# Supported OS: EL7
#
# Created by: Panxatony
#
#==============================================================================+

- name: Ensure NTP (for time synchronization) is installed.
  yum: name=ntp state=present
  become: yes
  become_user: root
  tags:
    - freeipa

- name: Ensure NTP is running.
  service: name=ntpd state=started enabled=yes
  become: yes
  become_user: root
  tags:
    - freeipa
